name: Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install and build
        run: |
          yarn install
          yarn build

      - name: Run unit tests
        run: |
          yarn test

      - name: Run E2E tests
        run: |
          yarn test:e2e

      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: reports/*.xml
